project_id = "zaeozfdjhrmblfaxsyuu"

[functions.create-first-admin]
verify_jwt = false

[functions.upsert-contact]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.email-webhook]
verify_jwt = false

[functions.get-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.execute-automations]
verify_jwt = true